#!/usr/bin/env ruby
# frozen_string_literal: true

target = '/home/sariel/prog/standards/workflow/bin/audit'
if File.exist?(target)
  if __FILE__ == $PROGRAM_NAME
    exec(target, *ARGV)
  else
    load target
  end
else
  warn "Audit standard not installed at #{target}"
  exit 0
end
